name: Release

permissions: {}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/extension-release.yml@35399afa8ac5fc7742f060c87dac485d74aa25d6 # v1.2.2
    permissions:
      contents: write
    with:
      go-version: "1.25.x"
      os: '["linux", "windows", "darwin"]'
      arch: '["amd64", "arm64"]'
      k6-version: "v1.3.0"
      xk6-version: "1.2.3"
      private: true
