name: Release

permissions: {}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/extension-release.yml@0099162985dd601cd68d44ed19771e45a0c3e2b1 # v1.2.3
    permissions:
      contents: write
    with:
      go-version: "1.25.x"
      os: '["linux", "windows", "darwin"]'
      arch: '["amd64", "arm64"]'
      k6-version: "v1.3.0"
      xk6-version: "1.2.3"
      private: true
